<?php
include('header.html');
?>
<div>
	<h4>Mentions légales et RGPD</h4>
	<p>Les données personnelles le cas échéant collectées via le formulaire de contact le sont pour assurer le traitement de votre demande de renseignement. Elles sont conservées pour une durée de cinq ans. Ces informations ne sont pas communiquées à des tiers en dehors du Groupe CCI Paris Ile-de-France et des collectivités locales partenaires. En cliquant sur "envoyer" vous consentez à ce que vos données soient utilisées à des fins de prospection et de communication par le groupe CCI Paris Île-de-France et ses collectivités locales partenaires. Les données personnelles éventuellement disponibles sur le site sont collectées pour permettre la mise en relation des porteurs de projet, commerçants, propriétaires de locaux et collectivités. Les données personnelles le cas échéant collectées sur l'interface d'administration du site le sont pour assurer la connexion et le bon fonctionnement du portail. Elles sont conservées le temps de votre utilisation du site.
		Conformément à la loi « informatique et libertés » du 6 janvier 1978 modifiée et au Règlement (UE) 2016-679 sur la protection des données, dans le cadre et les limites de ces textes, vous disposez d'un droit d'accès, de modification et de rectification relatif aux données vous concernant. Si vous avez consenti à ce que vos données soient utilisées à des fins de prospection et de communication, vous disposez également d’un droit de limitation, d'opposition et de suppression. Ces droits s'exercent en vous adressant à pdp.ddat@seineetmarne.cci.fr ou en écrivant à CCI Seine-et-Marne - Direction entreprises et territoires - Service données et analyses territoriales - 1 avenue Johannes Gutenberg – Serris - CS 70045 77776 Marne-la-Vallée Cedex 4. En cas de difficulté, vous pouvez vous adresser au délégué à la protection des données de la CCI Seine-et-Marne à l'adresse cpdp@cci-paris-idf.fr en précisant que la demande concerne des données personnelles détenues par la CCI Seine-et-Marne Direction entreprises et territoire - Service DAT. En dernier lieu, vous pouvez déposer une réclamation auprès de la CNIL 3 Place de Fontenoy - TSA 80715 - 75334 PARIS CEDEX 07.
	</p>
	<p>Editeur : Ce site Internet dédié aux boutiques éphémères est un site de la Chambre de Commerce et d'Industrie de Seine-et-Marne : 1 avenue Johannes Gutenberg - Serris - CS 70045 - 77776 Marne-la-Vallée Cedex 4.
		Directeur de publication : Jean-Charles HERRENSCHMIDT, Président de la CCI Seine-et-Marne.
		Responsable du site : Alain BEAUMONT, Directeur général adjoint appui entreprises et territoires.
		Hébergement : GIE Groupe CCIR Paris-Île-de-France, 47 rue de Tocqueville 75017 Paris, N°siret : 88929960800022.
		Reproduction sur support papier : A l’exception de l’iconographie, la reproduction des pages de ce site sur un support papier est autorisée, sous réserve du respect des trois conditions suivantes :
			gratuité de la diffusion, respect de l’intégrité des documents reproduits (aucune modification, ni altération d’aucune sorte), citation explicite du site https://boutiquesephemeres.cci77.fr/ comme source et mention que les droits de reproduction sont réservés et strictement limités.
		Reproduction sur support électronique : La reproduction de tout ou partie de ce site sur un support électronique est autorisée sous réserve de l’ajout de façon claire et lisible de la source (https://boutiquesephemeres.cci77.fr/) et de la mention « Droits réservés ». Les informations utilisées ne doivent l’être qu’à des fins personnelles, associatives ou professionnelles ; toute utilisation à des fins commerciales ou publicitaires est exclue.
		Création de liens : La CCI Seine-et-Marne autorise la mise en place d’un lien hypertexte pointant vers le contenu du site https://boutiquesephemeres.cci77.fr/, sous réserve de :
			ne pas utiliser la technique du lien profond (« deep linking »), c’est-à-dire que les pages du site https://boutiquesephemeres.cci77.fr/ ne doivent pas être imbriquées à l’intérieur des pages d’un autre site, mais accessible par l’ouverture d’une fenêtre, mentionner la source qui pointera grâce à un lien hypertexte directement sur le contenu visé. Les informations utilisées ne doivent l’être qu’à des fins personnelles, associatives ou professionnelles ; toute utilisation à des fins commerciales ou publicitaires est exclue.
		Attention. Cette autorisation ne s’applique pas aux sites internet diffusant des informations à caractère polémique, pornographique, xénophobe ou pouvant, dans une large mesure porter atteinte à la sensibilité du plus grand nombre. Pour d’autres utilisations, veuillez consulter le Responsable du site.
		Crédits : Les photographies sont propriétés de la CCI Seine-et-Marne.
	</p>
</div>

<?php
include('footer.html');
?>